### ISSUE TITLE
Carthage build fails

### ISSUE THREAD

**Issue by Hais** [Skogetroll/Result#1]
Library looks really useful! But I've unfortunately fallen at the first hurdle :(

```
$ echo 'github "Skogetroll/Result" >= 1.2.8"' > Cartfile
$ carthage version
0.12.0
$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Fetching Result
*** Checking out Result at "1.2.11"
*** xcodebuild output can be found in /var/folders/rg/lmss10b92qv7bhc_s5nt6hzh0000gn/T/carthage-xcodebuild.7NIu5B.log
*** Skipped building Result due to the error:
Dependency "Result" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Skogetroll/Result/issues/new
```

**Comment by Skogetroll** [comment]
Yeah, I was changing Travis CI building today and accidentally broke Carthage.

For now you can force it to use version `1.2.10`, which should work. 
Like `github "Skogetroll/Result" == 1.2.10"`.
This version builds, but it has problems with `WatchOS` and `tvOS` platforms, so it's better to use `carthage update/bootstrap --platform (ios | mac)`

But I hope this Carthage issue gonna be fixed soon. And it should fix `(Watch | tv)OS` problems too.

**Comment by Skogetroll** [comment]
@Hais Ok, now it has `shared framework scheme` and it builds fine for `Mac` platform.

But `iOS`, `tvOS` and `watchOS` compile only native binaries.

So I think i close this issue. And open another for that issue.

**Comment by Hais** [comment]
Sure. Thanks
